config/routes.rb
JustAddGirls::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/join' => 'users#join' #TODO: figure out how to automatically wire up causess conntroller
  match '/express-your-inner-geek' => 'causes#main', :as=> :main_cause
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def users
    @users = User.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.welcome
  .container
    .row-fluid.blurb
      .span5
        .row-fluid
          .span12
            %h2 Changing the conversation 17 syllables at a time
        .row-fluid.join
          .span12
            = link_to "Join", "/join", :class=>"loud" #TODO: Use button for this
      .span5.offset1
        #home-slider.carousel.slide
          .carousel-inner
            .active.item
              = image_tag("https://s3-us-west-1.amazonaws.com/jag-assets/images/beautiful_student.jpg")
              .carousel-caption
                %h4 Empower your creativity
                %p This is the place where you can be heard.
            .item
              #campaign-17s
              .carousel-caption
                %h4
                  = link_to "Express your inner geek",main_cause_path
                %p 
                  %strong Look, you're a geek.
                  We get it. Write a haiku and tell us about it.
                  = link_to "more", main_cause_path 

            .item
              = image_tag("https://s3-us-west-1.amazonaws.com/jag-assets/images/key_facts.png")
              .carousel-caption
                %h4 Topics
                %p Talk about politics, technology, comics, movies, sports, etc.
          %a.carousel-control.left{"data-slide" => "prev", :href => "#home-slider"} ‹
          %a.carousel-control.right{"data-slide" => "next", :href => "#home-slider"} ›
.explain
  .container
    .row-fluid
      .span4
        .row-fluid
          .span12
            = image_tag("https://s3-us-west-1.amazonaws.com/jag-assets/images/topics_rounded.jpg")
        .row-fluid.feature-highlight
          .span12
            %h4 Topics
            %p Find a topic that suits you.
      .span4
        .row-fluid
          .span12
            = image_tag("https://s3-us-west-1.amazonaws.com/jag-assets/images/jag_girl.png")
        .row-fluid.feature-highlight
          .span12
            %h4 Create
            %p Be creative. Express yourself.
      .span4
        .row-fluid
          .span12
            = image_tag("https://s3-us-west-1.amazonaws.com/jag-assets/images/haiku_rounded.jpg")
        .row-fluid.feature-highlight
          .span12
            %h4 Share
            %p This is where you can be yourself and get rewarded for doing so.
.showcase
  .container
    %h3 Featured Topic
    .featured-container
      %h2.featured-cause-name
        = link_to "Express your inner geek",main_cause_path
      .row-fluid.featured-content
        .span5
          .row-fluid
            .span12
              %h5
                %strong Look, you're a geek.
                %h5 We get it. Write a haiku and tell us about it.
          .featured-user
            = link_to image_tag('http://i.istockimg.com/file_thumbview_approve/19939420/1/stock-photo-19939420-color-portrait-of-a-charming-and-laughing-girl.jpg'), main_cause_path, :class => "feature-user-image"
            = link_to "Express your inner geek", main_cause_path
          .featured-statistics
            %p Influencers: 250
            %p Designers: 26
            %p Organizers: 53
        .span5.offset1
          = link_to image_tag("https://s3-us-west-1.amazonaws.com/jag-assets/images/geekitude.jpg", :class=>"featured-image") , main_cause_path
    .seperator
    %h4 Current Topics
    .row-fluid
      .span2.current-cause-container
        %h5 Accessing Water
        .img-circle
          = link_to image_tag("http://aidwatchers.com/wp/wp-content/uploads/2010/08/african-women-carrying-water.jpg", :class=>"current-image") , main_cause_path
        %p How can we make it easier for African families to obtain clean water? 
        = link_to image_tag('http://i.istockimg.com/file_thumbview_approve/19939420/1/stock-photo-19939420-color-portrait-of-a-charming-and-laughing-girl.jpg',:class => "current-user-image"), main_cause_path
        = link_to "jen_17s", main_cause_path
        .current-statistics
          %p Influencers: 125
          %p Designers: 3
          %p Organizers: 68
      .span2.offset1.current-cause-container
        %h5 Girls in Tech
        .img-circle
          = link_to image_tag("http://collegepals.org/wp-content/uploads/2011/12/computerGirl.jpg", :class=>"current-image") , main_cause_path
        %p The number of women entering the high tech workforce is on the rise. What can we do to improve...
        = link_to image_tag('https://s3-us-west-1.amazonaws.com/jag-assets/images/beautiful_student.jpg',:class => "current-user-image"), main_cause_path
        = link_to "irelandc90", main_cause_path
        .current-statistics
          %p Influencers: 252
          %p Designers: 8
          %p Organizers: 10
      .span2.offset1.current-cause-container
        %h5 Womens' Policy
        .img-circle
          = link_to image_tag("http://www.womenspolicy.org/images/content/pagebuilder/10533.jpg", :class=>"current-image") , main_cause_path
        %p Teach girls about local government and prepare them for making an impact on even bigger levels
        = link_to image_tag('http://thumb10.shutterstock.com/thumb_small/270058/95732242/stock-photo-closeup-portrait-of-elegant-middle-aged-woman-95732242.jpg',:class => "current-user-image"), main_cause_path
        = link_to "susronib", main_cause_path
        .current-statistics
          %p Influencers: 35
          %p Designers: 1
          %p Organizers: 6
      .span2.offset1.current-cause-container.outline
        %h5 Your Cause
        = image_tag("https://s3-us-west-1.amazonaws.com/jag-assets/images/jag_girl.png")
        .current-statistics
          %h6
            %strong Access to
          %p 1,000 influencers
          %p 230 designers
          %p 2,000 organizers

- content_for :before_body_close do
  :javascript
    $(function(){
     home_init(); 
    });

app/views/home/users.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}