config/routes.rb
JustAddGirls::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/join' => 'users#join' #TODO: figure out how to automatically wire up causess conntroller
  match '/express-your-inner-geek' => 'causes#main', :as=> :main_cause
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/views/layouts/_footer.html.haml
- unless current_page?(:action=>"join", :controller=>"users")
  %footer.container
    %ul.nav
      %li.active
        %a{:href => "#"} About
      %li
        %a{:href => "#"} Careers
      %li
        %a{:href => "#"} Reviews
      %li
        %a{:href => "#"} Help
      %li
        %a{:href => "#"} Blog
      %li 
        © #{Time.now.year} HaikuZa inc;
= javascript_include_tag "application"

app/views/layouts/_login.html.haml
%li.dropdown
  %a.dropdown-toggle.nav-profile{"data-toggle" => "dropdown", :href => "#"}
    = image_tag(current_user.profile_image_url,{:class=>"profile-image-nav"})
    %b.caret
  %ul.dropdown-menu
    %li
      = link_to 'Logout', signout_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
/ .btn-navbar is used as the toggle for collapsed navbar content
%a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar

= link_to root_path, :class => "brand" do #/TODO: find out why font sucks in windows
  %span.quiet-logo>Haiku
  %strong>Za

- unless current_page?(:action=>"join", :controller=>"users")
  - if current_page?(:action=>"index", :controller=>"home")
    .nav-collapse
      %ul.nav.nav-pills
        %li.active
          %a{:href => "#"} Home
        %li
          %a{:href => main_cause_path} Topics
        %li
          %a{:href => main_cause_path} People
        %li
          %a{:href => main_cause_path} Meetups
      %form.navbar-search.pull-right
        %input.search-query{:placeholder => "Search", :type => "text"}
      %ul.nav.nav-pills.pull-right
        - if user_signed_in?
          = render 'layouts/login'
        - else
          %li
            = link_to 'Login', signin_path
          %li.loud
            = link_to 'Join', "/join"
  - else
    .nav-collapse
      %ul.nav.nav-pills
        %li
          %a{:href => "#"} Home
        %li
          %a{:href => main_cause_path} Topics
        %li
          %a{:href => main_cause_path} People
        %li
          %a{:href => main_cause_path} Meetups
        %li
          = link_to 'Feedback', 'http://twitter.com/intent/tweet?hashtags=feedback&via=haiku_za', :class => "btn-inverse", :target => "_blank"
      %ul.nav.nav-pills.pull-right
        - if user_signed_in?
          = render 'layouts/login'
        - else
          %li
            = link_to 'Login', signin_path
          %li
            = link_to "/join" do
              %strong Join
      %form.navbar-search.pull-right
        %input.search-query{:placeholder => "Search", :type => "text"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "HaikuZa"
      %meta{:content => content_for?(:description) ? yield(:description) : "Just Add Girls", :name => "description"}
        %link{:href => "http://fonts.googleapis.com/css?family=Ubuntu|Molengo", :rel => "stylesheet", :type => "text/css"}
        = stylesheet_link_tag "application", :media => "all"
        = csrf_meta_tags
        = analytics_init if Rails.env.production?
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
      = yield
    = render 'layouts/footer'
    = yield(:before_body_close)